
CREATE TABLE CUSTOMER(CUSTID INT,CNAME VARCHAR(15),
LOCATION VARCHAR(12));
INSERT INTO CUSTOMER
VALUES(1,'NILIMA','PIMPRI'),
(2,'GANESH','PUNE'),
(3,'KISHOR','KOTHRUD'),
(4,'PRIYA','AUNDH');
SELECT * FROM CUSTOMER;
DELETE FROM CUSTOMER WHERE LOCATION='PIMPRI';
INSERT INTO CUSTOMER
VALUES(5,'GEETA','PIMPRI'),
(6,'RAJ','AUNDH'),
(7,'YASH','AUNDH');
DELETE FROM CUSTOMER WHERE LOCATION='AUNDH' AND CNAME='PRIYA';

